### ISSUE TITLE
Deploy to Huggingface's transformers

### ISSUE THREAD

**Issue by bui-thanh-lam** [nguyenvulebinh/vietnamese-roberta#1]
Chào anh,

Anh có suy nghĩ đến việc đưa model này lên thư viện transformers của Huggingface không ạ?

**Comment by nguyenvulebinh** [comment]
Mình đã đưa version envibert lên huggingface. Bạn có thể xem theo link này nhé! https://huggingface.co/nguyenvulebinh/envibert

**Comment by bui-thanh-lam** [comment]
Em đã dùng thử model này qua transformers. Có vẻ đây là một model rất cạnh tranh so với các pretrained cho tiếng Việt khác hiện nay (PhoBert, Vi-Electra...).
Cảm ơn anh rất nhiều.
P/s: Nếu anh đưa nốt bộ tokenizer lên huggingface được thì sẽ tiện lợi hơn nữa ạ.
